pipeline {
    agent { label 'ansible-controller' }
    environment {
        ANSIBLE_PRIVATE_KEY=credentials('ansible-private-key') 
        ANSIBLE_CONFIG='./Clase36/actividad/ansible/ansible.cfg'
    }
    stages {
        stage('Install Ansible collections'){
            steps {
                sh 'ansible-galaxy collection install -r ./Clase36/actividad/ansible/requirements.yml'
            }
        }
        stage('Run Ansible Playbook from Jenkins') {
            steps {
                sh 'ansible-playbook -i ./Clase36/actividad/ansible/inventory.ini --private-key=$ANSIBLE_PRIVATE_KEY ./Clase36/actividad/ansible/main.yml'
            }
        }
    }
}