- name: Deployment de un sitio estatico
  hosts: all
  become: yes
  pre_tasks:
    - name: Verificar si el OS es Ubuntu
      set_fact:
        is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"
  tasks:
    - name: Check if apache is running
      service:
        name: apache2
        state: started
        enabled: yes
      when: is_ubuntu